[package]
name = "systems"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
bevy_ecs = { version = "0.14.1" }
components = { path = "../components" }
log = "*"
rand = "0.8.5"

[features]
default = []
