[package]
name = "systems"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
bevy = { version = "0.14.1" }
bevy_dylib = "0.14.1"
components = { path = "../components" }
log = "*"
rand = "0.8.5"

[features]
default = []
dynamic = ["bevy/dynamic_linking", "components/dynamic"]
